spring.application.name=nebula-parfums

#Configuracion de base de datos mySql
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/nebula_parfums?seSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#Para exportar a PDF
spring.mvc.contentnegotiation.favor-parameter=true
spring.mvc.contentnegotiation.media-types.pdf=application/pdf


#Clave de jwt
jwt.secret=TQhrUnxBAniAJ74c6h94wbvl8xAmLFpGT9x8GnyxkQ1lpDI5Dq6M6UfQnFejtU4N


#Recuperar contrasena
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=contactohotelparaiso@gmail.com
spring.mail.password=yhmr qmyv pbrj jvxy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#Configuracion de paypal
paypal.client-id=AfEX6INYOJlUgMPqlT_7x7zPUyKggWMaleSXIdzqPjxb8QC8cnKsRdJSwtvumf2AQr4V1xKvopR7wOrz
paypal.client-secret=ENkdBK7k7IW4Vx3C3ArdTJsTzN84se7AbTCEV3SxWQFc9nmufoT98jcNHv4yAY4Ctm_rXjzPTFmlUbv7
paypal.base-url=https://api-m.sandbox.paypal.com